use_frameworks!

platform :ios, '12.0'

# pod 'DevPod', :path => '../../DevPod'

target 'WolfLocation_Example' do
  pod 'WolfLocation', :path => '../'

  target 'WolfLocation_Tests' do
    inherit! :search_paths
  end
end
